import type { Metadata } from "next";
import "@/styles/globals.css";
import { HeroUIProvider } from "@heroui/react";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "겜밋 | GAMEET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark min-h-screen flex flex-col">
        <Header />
        <HeroUIProvider className="flex flex-col flex-1 min-h-0 pt-[80px]">
          {children}
        </HeroUIProvider>
        <Footer />
      </body>
    </html>
  );
}
